source "https://rubygems.org"

gem "rake"
gem "mail", "~>2.4.4"
gem "mechanize", "~>2.5.1"
gem "mongo", "~>1.6.4"
gem "nokogiri", "~>1.5.5"
gem "daemons", "~>1.1.9"
gem "mongo_mapper", "~>0.11.2"
gem "bson_ext", "~>1.6.4"
gem "resque", "~>1.22.0"
gem "yajl-ruby"
gem "uuidtools", "~>2.1.3"
gem "liquid"
