mongodb:
  host: localhost
  port: 27017
  database: rare-find

mailer:
  from:                 your_email@gmail.com
  address:              smtp.gmail.com
  port:                 587
  domain:               localhost
  user_name:            your_email@gmail.com
  password:             your_password
  authentication:       plain
  enable_starttls_auto: true
